/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6ef6c88d-b253-4627-9ce7-398cecba392d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_H0XJwTX2r",
    "aws_user_pools_web_client_id": "3n0c9cmmt024q75j5fl1hbi9g4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xq7pfv3tnna5hjqq62swcfjici.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
